In [340]:
# %%
# =============================================================================
# 1. IMPORT LIBRARIES & SETUP
# =============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
sns.set_style("whitegrid")

print("✅ Libraries loaded")

✅ Libraries loaded

In [341]:
# %%
# =============================================================================
# 2. LOAD DATASETS (Update filenames if needed)
# =============================================================================
SOCIAL_FILE = "../data/raw/isoc_ci_ac_i__custom_21498829_linear_2_0.csv"
ECOMMERCE_FILE = "../data/raw/isoc_ec_ib20__custom_21518388_linear_2_0.csv"

sm = pd.read_csv(SOCIAL_FILE)
ec = pd.read_csv(ECOMMERCE_FILE)  # Update with your actual filename

print(f"📁 Loading: {SOCIAL_FILE}")
sm = pd.read_csv(SOCIAL_FILE)

print(f"📁 Loading: {ECOMMERCE_FILE}")
ec = pd.read_csv(ECOMMERCE_FILE)

print(f"\n✅ Loaded: Social Media ({sm.shape}), E-commerce ({ec.shape})")

📁 Loading: ../data/raw/isoc_ci_ac_i__custom_21498829_linear_2_0.csv
📁 Loading: ../data/raw/isoc_ec_ib20__custom_21518388_linear_2_0.csv

✅ Loaded: Social Media ((960, 21)), E-commerce ((595, 21))

In [342]:
sm.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_is,Information society indicator,unit,Unit of measure,ind_type,Individual type,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2020,NaN,86.32,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2021,NaN,77.86,NaN,b,break in time series,NaN,NaN
2,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2022,NaN,78.91,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2023,NaN,81.94,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2024,NaN,84.85,NaN,NaN,NaN,NaN,NaN

In [343]:
ec.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,ind_type,Individual type,indic_is,Information society indicator,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_B3_12,Last online purchase: between 3 and 12 months ago,PC_IND,Percentage of individuals,DE,Germany,2020,NaN,7.10,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_B3_12,Last online purchase: between 3 and 12 months ago,PC_IND,Percentage of individuals,DE,Germany,2021,NaN,6.11,NaN,b,break in time series,NaN,NaN
2,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_B3_12,Last online purchase: between 3 and 12 months ago,PC_IND,Percentage of individuals,DE,Germany,2022,NaN,9.13,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_B3_12,Last online purchase: between 3 and 12 months ago,PC_IND,Percentage of individuals,DE,Germany,2023,NaN,9.22,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_B3_12,Last online purchase: between 3 and 12 months ago,PC_IND,Percentage of individuals,DE,Germany,2024,NaN,10.72,NaN,NaN,NaN,NaN,NaN

In [344]:
sm.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'indic_is', 'Information society indicator', 'unit', 'Unit of measure',
       'ind_type', 'Individual type', 'geo', 'Geopolitical entity (reporting)',
       'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)'],
      dtype='str')

In [345]:
ec.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'ind_type', 'Individual type', 'indic_is',
       'Information society indicator', 'unit', 'Unit of measure', 'geo',
       'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time', 'OBS_VALUE',
       'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)'],
      dtype='str')

In [346]:
sm.isnull().sum()

STRUCTURE                                   0
STRUCTURE_ID                                0
STRUCTURE_NAME                              0
freq                                        0
Time frequency                              0
indic_is                                    0
Information society indicator               0
unit                                        0
Unit of measure                             0
ind_type                                    0
Individual type                             0
geo                                         0
Geopolitical entity (reporting)             0
TIME_PERIOD                                 0
Time                                      960
OBS_VALUE                                   0
Observation value                         960
OBS_FLAG                                  768
Observation status (Flag) V2 structure    768
CONF_STATUS                               960
Confidentiality status (flag)             960
dtype: int64

In [347]:
ec.isnull().sum()

STRUCTURE                                   0
STRUCTURE_ID                                0
STRUCTURE_NAME                              0
freq                                        0
Time frequency                              0
ind_type                                    0
Individual type                             0
indic_is                                    0
Information society indicator               0
unit                                        0
Unit of measure                             0
geo                                         0
Geopolitical entity (reporting)             0
TIME_PERIOD                                 0
Time                                      595
OBS_VALUE                                   2
Observation value                         595
OBS_FLAG                                  491
Observation status (Flag) V2 structure    491
CONF_STATUS                               595
Confidentiality status (flag)             595
dtype: int64

In [348]:
sm.isnull().sum().sum()

np.int64(5376)

In [349]:
ec.isnull().sum().sum()

np.int64(3364)

In [350]:
sm.groupby('TIME_PERIOD').apply(lambda x: x.isnull().sum().sum())

TIME_PERIOD
2020    960
2021    640
2022    960
2023    896
2024    960
2025    960
dtype: int64

In [351]:
ec.groupby('TIME_PERIOD').apply(lambda x: x.isnull().sum().sum())

TIME_PERIOD
2020    612
2021    510
2022    408
2023    714
2024    406
2025    714
dtype: int64

In [352]:
sm.shape

(960, 21)

In [353]:
ec.shape

(595, 21)

In [354]:
#to check if dataset is consistent
sm['TIME_PERIOD'].value_counts().sum()

np.int64(960)

In [355]:
sm.shape[0] == sm['TIME_PERIOD'].value_counts().sum()

np.True_

In [356]:
ec['TIME_PERIOD'].value_counts().sum()

np.int64(595)

In [357]:
ec.shape[0] == ec['TIME_PERIOD'].value_counts().sum()

np.True_

In [358]:
sm[sm['TIME_PERIOD'] == 2021].isnull().sum()

STRUCTURE                                   0
STRUCTURE_ID                                0
STRUCTURE_NAME                              0
freq                                        0
Time frequency                              0
indic_is                                    0
Information society indicator               0
unit                                        0
Unit of measure                             0
ind_type                                    0
Individual type                             0
geo                                         0
Geopolitical entity (reporting)             0
TIME_PERIOD                                 0
Time                                      160
OBS_VALUE                                   0
Observation value                         160
OBS_FLAG                                    0
Observation status (Flag) V2 structure      0
CONF_STATUS                               160
Confidentiality status (flag)             160
dtype: int64

In [359]:
ec[ec['TIME_PERIOD'] == 2021].isnull().sum()

STRUCTURE                                   0
STRUCTURE_ID                                0
STRUCTURE_NAME                              0
freq                                        0
Time frequency                              0
ind_type                                    0
Individual type                             0
indic_is                                    0
Information society indicator               0
unit                                        0
Unit of measure                             0
geo                                         0
Geopolitical entity (reporting)             0
TIME_PERIOD                                 0
Time                                      119
OBS_VALUE                                   0
Observation value                         119
OBS_FLAG                                   17
Observation status (Flag) V2 structure     17
CONF_STATUS                               119
Confidentiality status (flag)             119
dtype: int64

In [360]:
sm1 = sm
ec2 = ec
sm1.shape, ec2.shape
sm1.columns.equals(ec2.columns)

False

In [361]:
set(sm1.columns) - set(ec2.columns)

set()

In [362]:
set(ec2.columns) - set(sm1.columns)

set()

🧠 CLEAN ANALYSIS PIPELINE
🎯 Goal reminder

I am analyzing:

Digital engagement (social media use)
vs
E-commerce behavior (online shopping)
in Germany (2020–2025)

So I treat this as:

two parallel datasets
aligned later only at aggregated level

🧩 STEP 1 — Load & standardize

In [363]:
#clean column names
sm.columns = sm.columns.str.strip()
ec.columns = ec.columns.str.strip()

In [364]:
#Ensure consistent filtering (Germany only check)
sm = sm[sm['geo'] == 'DE']
ec = ec[ec['geo'] == 'DE']

🧹 STEP 2 — Handle missing values

In [365]:
#Add missing flags (VERY important for transparency)
sm['missing_flag'] = sm['OBS_VALUE'].isna()
ec['missing_flag'] = ec['OBS_VALUE'].isna()

In [366]:
#Keep realism (Eurostat is incomplete by design)
#Instead of deleting everything
#remove rows where the actual value is missing
sm = sm.dropna(subset=['OBS_VALUE'])
ec = ec.dropna(subset=['OBS_VALUE'])

🧱 STEP 3 — Standardize structure 

Remove Eurostat metadata noise and keep analysis-ready fields.
Remove:
STRUCTURE
STRUCTURE_ID
STRUCTURE_NAME
freq
Time frequency
Time
Observation value
Observation status (Flag) V2 structure
Confidentiality status (flag)

In [367]:
sm.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'indic_is', 'Information society indicator', 'unit', 'Unit of measure',
       'ind_type', 'Individual type', 'geo', 'Geopolitical entity (reporting)',
       'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)', 'missing_flag'],
      dtype='str')

In [368]:
ec.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'ind_type', 'Individual type', 'indic_is',
       'Information society indicator', 'unit', 'Unit of measure', 'geo',
       'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time', 'OBS_VALUE',
       'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)', 'missing_flag'],
      dtype='str')

In [369]:
set(sm.columns) == set(ec.columns)

True

In [370]:
keep_cols = [
'indic_is',
'Information society indicator',

'ind_type',
'Individual type',

'unit',

'geo',

'TIME_PERIOD',

'OBS_VALUE',

'OBS_FLAG',

'CONF_STATUS'
]

In [371]:
sm = sm[keep_cols].copy()
ec = ec[keep_cols].copy()

Rename to analysis names

In [372]:
rename_dict = {
'indic_is':'indicator_code',
'Information society indicator':'indicator',
'ind_type':'demo_code',
'Individual type':'demographic',
'unit':'unit',
'geo':'country',
'TIME_PERIOD':'year',
'OBS_VALUE':'value',
'OBS_FLAG':'obs_flag',
'CONF_STATUS':'conf_status'
}

sm.rename(columns=rename_dict,inplace=True)
ec.rename(columns=rename_dict,inplace=True)

In [373]:
sm.columns

Index(['indicator_code', 'indicator', 'demo_code', 'demographic', 'unit',
       'country', 'year', 'value', 'obs_flag', 'conf_status'],
      dtype='str')

In [374]:
ec.columns

Index(['indicator_code', 'indicator', 'demo_code', 'demographic', 'unit',
       'country', 'year', 'value', 'obs_flag', 'conf_status'],
      dtype='str')

📊 STEP 4 — REDUCE TO ANALYSIS VARIABLES

Now reduce based on my research question, not dataset size.

RQ needs:

social engagement
shopping frequency
age
gender
education
time

In [375]:
#social media indicators

sm_keep = [
'I_IUSNET',   # social networks

'I_IUIF',     # goods info search

'I_IUEM',     # email

'I_IUNW1'     # news
]

In [376]:
#filter
sm = sm[
sm['indicator_code'].isin(sm_keep)
]

In [377]:
social_indicator_map = {
'I_IUSNET':'Social Media Participation',
'I_IUIF':'Product Information search',
'I_IUEM':'Email Usage',
'I_IUNW1':'Online News Reading'

}

In [378]:
sm['indicator_name'] = sm['indicator_code'].replace(
social_indicator_map
)

E-commerce Indicators

In [379]:
ec_keep =[
'I_BF_1_2',
'I_BF_3-5',
'I_BF_6-10',
'I_BF_GT10',
'I_BUX'
]

#FILTER
ec = ec[
ec['indicator_code'].isin(ec_keep)
]

In [380]:
ecommerce_indicator_map = {

    'I_BF_1_2': 'Low Purchase Frequency (1–2 purchases)',

    'I_BF_3-5': 'Moderate Purchase Frequency (3–5 purchases)',

    'I_BF_6-10': 'High Purchase Frequency (6–10 purchases)',

    'I_BF_GT10': 'Very High Purchase Frequency (10+ purchases)',

    'I_BUX': 'Never Purchased Online'
}

ec['indicator_name'] = ec['indicator_code'].replace(
    ecommerce_indicator_map
)

Keep both indicator_code and indicator_name in the cleaned dataset — the code helps trace back to Eurostat, while the name is use in charts, Tableau, and the report.

📊 STEP 5 - Demographic Filtering

In [381]:
#Step 1- Create demographic category
#this function is labeling into groups
#It will help to analyze columns.

def classify_demo(x):

    x = str(x)

    if x.startswith('Y'):
        return 'Age'

    elif x in ['M','F']:
        return 'Gender'

    elif x.startswith('ED'):
        return 'Education'

    else:
        return 'Other'
    
sm['demo_type'] = sm['demo_code'].apply(classify_demo)

ec['demo_type'] = ec['demo_code'].apply(classify_demo)

In [382]:
#Step 2 -- Create readable demographic labels

demo_label_map = {
    #age
    'Y16_24':'Age 16-24',
    'Y25_54':'Age 25-54',
    'Y55_74':'Age 55-74',

    #gender
    'M':'Male',
    'F':'Female',

    #education
    'ED0-2':'Low Education',
    'ED3-4':'Medium Education',
    'ED5-8':'High Education'
}

#apply

sm['demo_label'] = sm['demo_code'].replace(
    demo_label_map
)

ec['demo_label'] = ec['demo_code'].replace(
    demo_label_map
)

In [383]:
#keep only project demographics

valid_demo = list(demo_label_map.keys())

sm = sm[
    sm['demo_code'].isin(valid_demo)
]
ec = ec[
    ec['demo_code'].isin(valid_demo)
]

In [384]:
#Age analysis

sm_age = sm[
    sm['demo_type']== 'Age'
]

In [385]:
#gender

ec_gender = ec[
    ec['demo_type']=='Gender'
]

In [386]:
#Education

sm_edu = sm[
    sm['demo_type']=='Education'
]

In [387]:
sm['value'].head(10)

12     93.72
13     87.87
14     84.50
15     87.43
16     89.87
17     91.08
108    94.53
109    90.10
110    87.68
111    90.35
Name: value, dtype: float64

In [388]:
ec['value'].head(10)

111    31.98
112    22.81
113    25.35
114    23.68
115    13.30
116    12.04
117    13.00
118    12.14
119    10.45
120    11.22
Name: value, dtype: float64

In [389]:
ec[
[
'year',
'indicator_name',
'demo_label',
'value'
]
].head(20)

     year                                indicator_name demo_label  value
111  2020   Moderate Purchase Frequency (3–5 purchases)  Age 16-24  31.98
112  2021   Moderate Purchase Frequency (3–5 purchases)  Age 16-24  22.81
113  2023   Moderate Purchase Frequency (3–5 purchases)  Age 16-24  25.35
114  2025   Moderate Purchase Frequency (3–5 purchases)  Age 16-24  23.68
115  2020      High Purchase Frequency (6–10 purchases)  Age 16-24  13.30
116  2021      High Purchase Frequency (6–10 purchases)  Age 16-24  12.04
117  2023      High Purchase Frequency (6–10 purchases)  Age 16-24  13.00
118  2025      High Purchase Frequency (6–10 purchases)  Age 16-24  12.14
119  2020  Very High Purchase Frequency (10+ purchases)  Age 16-24  10.45
120  2021  Very High Purchase Frequency (10+ purchases)  Age 16-24  11.22
121  2023  Very High Purchase Frequency (10+ purchases)  Age 16-24   9.61
122  2025  Very High Purchase Frequency (10+ purchases)  Age 16-24  10.88
251  2020   Moderate Purchase Frequency (3–5 purchases)  Age 25-54  29.14
252  2021   Moderate Purchase Frequency (3–5 purchases)  Age 25-54  21.90
253  2023   Moderate Purchase Frequency (3–5 purchases)  Age 25-54  23.19
254  2025   Moderate Purchase Frequency (3–5 purchases)  Age 25-54  24.11
255  2020      High Purchase Frequency (6–10 purchases)  Age 25-54  18.79
256  2021      High Purchase Frequency (6–10 purchases)  Age 25-54  12.10
257  2023      High Purchase Frequency (6–10 purchases)  Age 25-54  13.14
258  2025      High Purchase Frequency (6–10 purchases)  Age 25-54  13.91

In [390]:
print("SM rows:", len(sm))
print("EC rows:", len(ec))

SM rows: 48
EC rows: 36

In [391]:
sm.groupby(['year','demo_type']).size()

ec.groupby(['year','demo_type']).size()

year  demo_type
2020  Age          9
2021  Age          9
2023  Age          9
2025  Age          9
dtype: int64

In [392]:
sm['indicator_name'].value_counts()

ec['indicator_name'].value_counts()

indicator_name
Moderate Purchase Frequency (3–5 purchases)     12
High Purchase Frequency (6–10 purchases)        12
Very High Purchase Frequency (10+ purchases)    12
Name: count, dtype: int64

In [393]:
sm['demo_code'].value_counts()

ec['demo_code'].value_counts()

demo_code
Y16_24    12
Y25_54    12
Y55_74    12
Name: count, dtype: int64

In [394]:
sm['year'].value_counts().sort_index()

ec['year'].value_counts().sort_index()

year
2020    9
2021    9
2023    9
2025    9
Name: count, dtype: int64

In [395]:
sm[['demo_code','demo_type']].drop_duplicates()

ec[['demo_code','demo_type']].drop_duplicates()

    demo_code demo_type
111    Y16_24       Age
251    Y25_54       Age
461    Y55_74       Age

In [396]:
sorted(sm['demo_code'].unique())

sorted(ec['demo_code'].unique())

['Y16_24', 'Y25_54', 'Y55_74']

In [397]:
sorted(sm['year'].unique())

sorted(ec['year'].unique())

[np.int64(2020), np.int64(2021), np.int64(2023), np.int64(2025)]

### Start fresh from the raw files / original DataFrames

In [398]:
sm = sm1.copy()
ec = ec2.copy()

In [399]:
ec = ec[
    (ec['geo']=='DE') &
    (ec['TIME_PERIOD'].isin([2020,2021,2022,2023,2024,2025])) &
    (ec['unit']=='PC_IND')
]

ec['TIME_PERIOD'].value_counts().sort_index()

TIME_PERIOD
2020    102
2021    119
2022     68
2023    119
2024     68
2025    119
Name: count, dtype: int64

In [400]:
sm.columns = sm.columns.str.strip()
ec.columns = ec.columns.str.strip()

In [401]:
sm[['ind_type', 'Individual type']].drop_duplicates()

             ind_type                                    Individual type
0            F_Y16_74                        Females, 16 to 74 years old
6            M_Y16_74                          Males, 16 to 74 years old
12             Y16_24                    Individuals, 16 to 24 years old
18           Y16_24HI  Individuals aged 16-24 with high formal education
24           Y16_24LO          Individuals aged 16-24 with low education
30           Y16_24ME  Individuals aged 16-24 with medium formal educ...
36           Y25_54HI  Individuals aged 25 to 54 with high formal edu...
42           Y25_54LO  Individuals aged 25 to 54 with low formal educ...
48           Y25_54ME  Individuals aged 25 to 54 with medium formal e...
54             Y25_64                    Individuals, 25 to 64 years old
60  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
66         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed
72           Y55_74HI  Individuals aged 55 to 74 with high formal edu...
78           Y55_74LO  Individuals aged 55 to 74 with low formal educ...
84           Y55_74ME  Individuals aged 55 to 74 with medium formal e...
90             Y65_74                    Individuals, 65 to 74 years old

In [402]:
ec[['ind_type', 'Individual type']].drop_duplicates()

              ind_type                                    Individual type
0             F_Y16_74                        Females, 16 to 74 years old
35           IND_TOTAL                                    All individuals
70            M_Y16_74                          Males, 16 to 74 years old
105             Y16_24                    Individuals, 16 to 24 years old
140           Y16_24HI  Individuals aged 16-24 with high formal education
175           Y16_24LO          Individuals aged 16-24 with low education
210           Y16_24ME  Individuals aged 16-24 with medium formal educ...
245             Y25_54                    Individuals, 25 to 54 years old
280           Y25_54HI  Individuals aged 25 to 54 with high formal edu...
315           Y25_54LO  Individuals aged 25 to 54 with low formal educ...
350           Y25_54ME  Individuals aged 25 to 54 with medium formal e...
385  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
420         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed
455             Y55_74                    Individuals, 55 to 74 years old
490           Y55_74HI  Individuals aged 55 to 74 with high formal edu...
525           Y55_74LO  Individuals aged 55 to 74 with low formal educ...
560           Y55_74ME  Individuals aged 55 to 74 with medium formal e...

In [403]:
sm['missing_flag'] = sm['OBS_VALUE'].isna()
ec['missing_flag'] = ec['OBS_VALUE'].isna()

In [404]:
sm = sm.dropna(subset=['OBS_VALUE'])
ec = ec.dropna(subset=['OBS_VALUE'])

In [405]:
rename_dict = {
    'indic_is': 'indicator_code',
    'Information society indicator': 'indicator',
    'ind_type': 'demo_code',
    'Individual type': 'demographic',
    'unit': 'unit',
    'geo': 'country',
    'TIME_PERIOD': 'year',
    'OBS_VALUE': 'value',
    'OBS_FLAG': 'obs_flag',
    'CONF_STATUS': 'conf_status'
}

sm = sm.rename(columns=rename_dict)
ec = ec.rename(columns=rename_dict)

In [406]:
valid_years = [2020, 2021, 2022, 2023, 2024, 2025]

sm = sm[(sm['country'] == 'DE') & (sm['year'].isin(valid_years)) & (sm['unit'] == 'PC_IND')]
ec = ec[(ec['country'] == 'DE') & (ec['year'].isin(valid_years)) & (ec['unit'] == 'PC_IND')]

In [407]:
sm_keep = ['I_IUSNET', 'I_IUIF', 'I_IUEM', 'I_IUNW1']

ec_keep = ['I_BF_1_2', 'I_BF_3-5', 'I_BF_6-10', 'I_BF_GT10', 'I_BUX']

sm = sm[sm['indicator_code'].isin(sm_keep)]
ec = ec[ec['indicator_code'].isin(ec_keep)]

In [408]:
def classify_demo(code, label):
    code = str(code)
    label = str(label).lower()

    if code.startswith('Y'):
        return 'Age'
    elif code.startswith('M') or code.startswith('F') or 'male' in label or 'female' in label:
        return 'Gender'
    elif code.startswith('ED') or 'education' in label:
        return 'Education'
    else:
        return 'Other'

In [409]:
sm['demo_type'] = sm.apply(lambda row: classify_demo(row['demo_code'], row['demographic']), axis=1)

ec['demo_type'] = ec.apply(lambda row: classify_demo(row['demo_code'], row['demographic']), axis=1)

In [410]:
sm[['demo_code', 'demographic', 'demo_type']].drop_duplicates()

,demo_code,demographic,demo_type
0,F_Y16_74,"Females, 16 to 74 years old",Gender
6,M_Y16_74,"Males, 16 to 74 years old",Gender
12,Y16_24,"Individuals, 16 to 24 years old",Age
18,Y16_24HI,Individuals aged 16-24 with high formal education,Age
24,Y16_24LO,Individuals aged 16-24 with low education,Age
30,Y16_24ME,Individuals aged 16-24 with medium formal educ...,Age
36,Y25_54HI,Individuals aged 25 to 54 with high formal edu...,Age
42,Y25_54LO,Individuals aged 25 to 54 with low formal educ...,Age
48,Y25_54ME,Individuals aged 25 to 54 with medium formal e...,Age
54,Y25_64,"Individuals, 25 to 64 years old",Age
60,Y25_64_SALSELFFAM,"Individuals aged 25 to 64 who are employees, s...",Age
66,Y25_64_UNE,Individuals aged 25 to 64 who are unemployed,Age
72,Y55_74HI,Individuals aged 55 to 74 with high formal edu...,Age
78,Y55_74LO,Individuals aged 55 to 74 with low formal educ...,Age
84,Y55_74ME,Individuals aged 55 to 74 with medium formal e...,Age
90,Y65_74,"Individuals, 65 to 74 years old",Age

In [411]:
ec[['demo_code', 'demographic', 'demo_type']].drop_duplicates()

,demo_code,demographic,demo_type
6,F_Y16_74,"Females, 16 to 74 years old",Gender
41,IND_TOTAL,All individuals,Other
76,M_Y16_74,"Males, 16 to 74 years old",Gender
111,Y16_24,"Individuals, 16 to 24 years old",Age
146,Y16_24HI,Individuals aged 16-24 with high formal education,Age
181,Y16_24LO,Individuals aged 16-24 with low education,Age
216,Y16_24ME,Individuals aged 16-24 with medium formal educ...,Age
251,Y25_54,"Individuals, 25 to 54 years old",Age
286,Y25_54HI,Individuals aged 25 to 54 with high formal edu...,Age
321,Y25_54LO,Individuals aged 25 to 54 with low formal educ...,Age
356,Y25_54ME,Individuals aged 25 to 54 with medium formal e...,Age
391,Y25_64_SALSELFFAM,"Individuals aged 25 to 64 who are employees, s...",Age
426,Y25_64_UNE,Individuals aged 25 to 64 who are unemployed,Age
461,Y55_74,"Individuals, 55 to 74 years old",Age
496,Y55_74HI,Individuals aged 55 to 74 with high formal edu...,Age
531,Y55_74LO,Individuals aged 55 to 74 with low formal educ...,Age
566,Y55_74ME,Individuals aged 55 to 74 with medium formal e...,Age

In [412]:
print(sm.shape)
print(ec.shape)

print(sm['demo_type'].value_counts())
print(ec['demo_type'].value_counts())

print(sm['year'].value_counts().sort_index())
print(ec['year'].value_counts().sort_index())

(384, 23)
(204, 23)
demo_type
Age       336
Gender     48
Name: count, dtype: int64
demo_type
Age       168
Gender     24
Other      12
Name: count, dtype: int64
year
2020    64
2021    64
2022    64
2023    64
2024    64
2025    64
Name: count, dtype: int64
year
2020    51
2021    51
2023    51
2025    51
Name: count, dtype: int64

In [413]:
sm[
['demo_code','demographic','demo_type']
].drop_duplicates().sort_values(
'demo_type'
)

,demo_code,demographic,demo_type
12,Y16_24,"Individuals, 16 to 24 years old",Age
18,Y16_24HI,Individuals aged 16-24 with high formal education,Age
24,Y16_24LO,Individuals aged 16-24 with low education,Age
30,Y16_24ME,Individuals aged 16-24 with medium formal educ...,Age
36,Y25_54HI,Individuals aged 25 to 54 with high formal edu...,Age
42,Y25_54LO,Individuals aged 25 to 54 with low formal educ...,Age
48,Y25_54ME,Individuals aged 25 to 54 with medium formal e...,Age
54,Y25_64,"Individuals, 25 to 64 years old",Age
60,Y25_64_SALSELFFAM,"Individuals aged 25 to 64 who are employees, s...",Age
66,Y25_64_UNE,Individuals aged 25 to 64 who are unemployed,Age
72,Y55_74HI,Individuals aged 55 to 74 with high formal edu...,Age
78,Y55_74LO,Individuals aged 55 to 74 with low formal educ...,Age
84,Y55_74ME,Individuals aged 55 to 74 with medium formal e...,Age
90,Y65_74,"Individuals, 65 to 74 years old",Age
0,F_Y16_74,"Females, 16 to 74 years old",Gender
6,M_Y16_74,"Males, 16 to 74 years old",Gender

In [414]:
ec[
ec['demo_type']=='Other'
][
['demo_code','demographic']
].drop_duplicates()

    demo_code      demographic
41  IND_TOTAL  All individuals

In [415]:
sm[
sm['demo_type']=='Education'
][
['demo_code','demographic']
].drop_duplicates()

Empty DataFrame
Columns: [demo_code, demographic]
Index: []

In [416]:
sorted(ec2['TIME_PERIOD'].unique())

[np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025)]

In [417]:
ec[
ec['year'].isin([2022,2024])
][
[
'year',
'indicator_code',
'demo_code',
'value'
]
]

Empty DataFrame
Columns: [year, indicator_code, demo_code, value]
Index: []

In [418]:
ec[
ec['year'].isin([2022,2024])
]['indicator_code'].value_counts()

Series([], Name: count, dtype: int64)

In [419]:
ec[
ec['year'].isin([2022,2024])
]['demo_code'].value_counts()

Series([], Name: count, dtype: int64)

— Load Education-Segmented Datasets

## Why?

The original datasets contained:

- Age groups
- Gender groups

However, education segmentation was missing from the exported files.

To strengthen demographic analysis and support the research objective, additional education-segmented datasets were downloaded from the same Eurostat tables.

The education download contains combined demographic groups:

- Age + Low education
- Age + Medium education
- Age + High education

Examples:

- Y16_24LO → Age 16–24 + Low education
- Y25_54ME → Age 25–54 + Medium education
- Y55_74HI → Age 55–74 + High education

This improves segmentation depth and enables demographic marketing analysis.

In [420]:
ec_edu = pd.read_csv(
    "../data/raw/isoc_ec_ib20__custom_21581176_linear_2_0_new.csv"
)
sm_edu = pd.read_csv(
    "../data/raw/isoc_ci_ac_i__custom_21581169_linear_2_0_new.csv"
)

# — Create Working Copies

## Why?

Raw datasets should remain untouched.

Working copies allow cleaning operations without modifying original files.

Structure:

sm_edu → raw education dataset

sm_edu1 → cleaned working version

In [421]:
sm_edu1 = sm_edu.copy()

ec_edu1 = ec_edu.copy()

# — Remove Missing Observation Values

## Why?

OBS_VALUE represents the percentage value used in analysis.

Examples:

91.2 → 91.2% social media participation

43.5 → 43.5% online shopping participation

Rows with missing OBS_VALUE cannot be used in:

- trend analysis
- correlation
- segmentation
- dashboard construction

Therefore missing observation rows are removed.

In [422]:
sm_edu1 = sm_edu1.dropna(
    subset=['OBS_VALUE']
)

ec_edu1 = ec_edu1.dropna(
    subset=['OBS_VALUE']
)

# STEP 20 — Standardize Column Names

## Why?

Eurostat uses technical names.

Renaming improves readability and consistency across datasets.

Examples:

indic_is → indicator_code

ind_type → demo_code

TIME_PERIOD → year

OBS_VALUE → value

In [423]:
rename_dict = {

    'indic_is':'indicator_code',

    'Information society indicator':'indicator',

    'ind_type':'demo_code',

    'Individual type':'demographic',

    'geo':'country',

    'TIME_PERIOD':'year',

    'OBS_VALUE':'value'
}

sm_edu1 = sm_edu1.rename(
    columns=rename_dict
)

ec_edu1 = ec_edu1.rename(
    columns=rename_dict
)

# — Inspect Education Demographic Codes

## Why?

Before filtering or classification, demographic codes must be verified.

This avoids assumptions and ensures correct grouping.

Expected codes:

Y16_24LO

Y16_24ME

Y16_24HI

Y25_54LO

Y25_54ME

Y25_54HI

Y55_74LO

Y55_74ME

Y55_74HI

In [424]:
sm_edu1[
[
'demo_code',
'demographic'
]
].drop_duplicates()

            demo_code                                        demographic
0            Y16_24HI  Individuals aged 16-24 with high formal education
6            Y16_24LO          Individuals aged 16-24 with low education
12           Y16_24ME  Individuals aged 16-24 with medium formal educ...
18           Y25_54HI  Individuals aged 25 to 54 with high formal edu...
24           Y25_54LO  Individuals aged 25 to 54 with low formal educ...
30           Y25_54ME  Individuals aged 25 to 54 with medium formal e...
36  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
42         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed
48           Y55_74HI  Individuals aged 55 to 74 with high formal edu...
54           Y55_74LO  Individuals aged 55 to 74 with low formal educ...
60           Y55_74ME  Individuals aged 55 to 74 with medium formal e...

In [425]:
ec_edu1[
[
'demo_code',
'demographic'
]
].drop_duplicates()

             demo_code                                        demographic
0             Y16_24HI  Individuals aged 16-24 with high formal education
35            Y16_24LO          Individuals aged 16-24 with low education
70            Y16_24ME  Individuals aged 16-24 with medium formal educ...
105           Y25_54HI  Individuals aged 25 to 54 with high formal edu...
140           Y25_54LO  Individuals aged 25 to 54 with low formal educ...
175           Y25_54ME  Individuals aged 25 to 54 with medium formal e...
210  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
245         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed
280           Y55_74HI  Individuals aged 55 to 74 with high formal edu...
315           Y55_74LO  Individuals aged 55 to 74 with low formal educ...
350           Y55_74ME  Individuals aged 55 to 74 with medium formal e...

# — Create Education Categories

## Why?

Raw demographic codes combine age and education.

Example:

Y25_54HI

contains:

Age = 25–54

Education = High

A separate education variable improves segmentation analysis.

In [426]:
def classify_edu(x):

    x = str(x)

    if x.endswith('LO'):
        return 'Low Education'

    elif x.endswith('ME'):
        return 'Medium Education'

    elif x.endswith('HI'):
        return 'High Education'

    else:
        return 'Other'

In [427]:
sm_edu1[
'education_level'
] = sm_edu1[
'demo_code'
].apply(
classify_edu
)

ec_edu1[
'education_level'
] = ec_edu1[
'demo_code'
].apply(
classify_edu
)

#  — Combine Demographic Datasets

## Why?

Original datasets:

Age + Gender

New datasets:

Age + Education

Combining them creates a richer demographic dataset for final analysis.

Final demographic dimensions:

- Age
- Gender
- Education

In [428]:
sm_final = pd.concat(
[
sm,
sm_edu1
],
ignore_index=True
)

ec_final = pd.concat(
[
ec,
ec_edu1
],
ignore_index=True
)

# — Validate Final Dataset

## Why?

Validation confirms:

- expected row counts
- successful merge
- education categories exist
- no demographic loss occurred

In [429]:
sm_final.shape

ec_final.shape

(587, 26)

In [430]:
sm_final[
'education_level'
].value_counts()

education_level
High Education      180
Low Education       180
Medium Education    180
Other               120
Name: count, dtype: int64

In [431]:
ec_final[
'education_level'
].value_counts()

education_level
Low Education       105
Medium Education    105
High Education      103
Other                70
Name: count, dtype: int64

# — Remove Employment Demographics

## Why?

During education dataset integration, additional employment-status demographic groups were identified.

Detected groups:

Y25_64_SALSELFFAM

→ Individuals aged 25–64 who are employees, self-employed or family workers

Y25_64_UNE

→ Individuals aged 25–64 who are unemployed

These groups were excluded because they introduce a new demographic dimension (employment status) outside the research scope.

Final demographic dimensions retained:

- Age
- Gender
- Education

Removing employment groups preserves analytical consistency and avoids scope expansion.

In [432]:
sm_final[
sm_final['education_level']=='Other'
][
[
'demo_code',
'demographic'
]
].drop_duplicates()

             demo_code                                        demographic
420  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
426         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed

In [433]:
ec_final[
ec_final['education_level']=='Other'
][
[
'demo_code',
'demographic'
]
].drop_duplicates()

             demo_code                                        demographic
412  Y25_64_SALSELFFAM  Individuals aged 25 to 64 who are employees, s...
447         Y25_64_UNE       Individuals aged 25 to 64 who are unemployed

In [434]:
remove_emp = [
'Y25_64_SALSELFFAM',
'Y25_64_UNE'
]

sm_final = sm_final[
~sm_final['demo_code'].isin(
remove_emp
)
]

ec_final = ec_final[
~ec_final['demo_code'].isin(
remove_emp
)
]

In [435]:
sm_final[
'education_level'
].value_counts()

education_level
High Education      180
Low Education       180
Medium Education    180
Name: count, dtype: int64

In [436]:
ec_final[
'education_level'
].value_counts()

education_level
Low Education       105
Medium Education    105
High Education      103
Name: count, dtype: int64

# — Final Dataset Validation

## Why?

A final validation step was performed after demographic integration and employment-group removal.

Validation objectives:

- confirm demographic completeness
- verify year coverage
- confirm successful education integration
- ensure employment groups were removed

Final demographic dimensions retained:

Age:
Y16_24
Y25_54
Y55_74

Gender:
F_Y16_74
M_Y16_74

Education:

Low:
Y16_24LO
Y25_54LO
Y55_74LO

Medium:
Y16_24ME
Y25_54ME
Y55_74ME

High:
Y16_24HI
Y25_54HI
Y55_74HI

Excluded:

Y25_64_SALSELFFAM

Y25_64_UNE

In [437]:
sm_final.shape

ec_final.shape

(493, 26)

In [438]:
sm_final['year'].value_counts().sort_index()

ec_final['year'].value_counts().sort_index()

year
2020     99
2021    108
2022     36
2023    108
2024     34
2025    108
Name: count, dtype: int64

In [439]:
sm_final[
[
'demo_code',
'education_level'
]
].drop_duplicates()

    demo_code   education_level
0    F_Y16_74               NaN
6    M_Y16_74               NaN
12     Y16_24               NaN
18   Y16_24HI               NaN
24   Y16_24LO               NaN
30   Y16_24ME               NaN
36   Y25_54HI               NaN
42   Y25_54LO               NaN
48   Y25_54ME               NaN
54     Y25_64               NaN
72   Y55_74HI               NaN
78   Y55_74LO               NaN
84   Y55_74ME               NaN
90     Y65_74               NaN
384  Y16_24HI    High Education
390  Y16_24LO     Low Education
396  Y16_24ME  Medium Education
402  Y25_54HI    High Education
408  Y25_54LO     Low Education
414  Y25_54ME  Medium Education
432  Y55_74HI    High Education
438  Y55_74LO     Low Education
444  Y55_74ME  Medium Education

In [440]:
ec_final[
[
'demo_code',
'education_level'
]
].drop_duplicates()

     demo_code   education_level
0     F_Y16_74               NaN
12   IND_TOTAL               NaN
24    M_Y16_74               NaN
36      Y16_24               NaN
48    Y16_24HI               NaN
60    Y16_24LO               NaN
72    Y16_24ME               NaN
84      Y25_54               NaN
96    Y25_54HI               NaN
108   Y25_54LO               NaN
120   Y25_54ME               NaN
156     Y55_74               NaN
168   Y55_74HI               NaN
180   Y55_74LO               NaN
192   Y55_74ME               NaN
204   Y16_24HI    High Education
237   Y16_24LO     Low Education
272   Y16_24ME  Medium Education
307   Y25_54HI    High Education
342   Y25_54LO     Low Education
377   Y25_54ME  Medium Education
482   Y55_74HI    High Education
517   Y55_74LO     Low Education
552   Y55_74ME  Medium Education

In [441]:
sm_final['education_level'] = sm_final[
'education_level'
].fillna('Not Education Segment')

ec_final['education_level'] = ec_final[
'education_level'
].fillna('Not Education Segment')

In [442]:
remove_age = [
'Y25_64',
'Y65_74'
]

sm_final = sm_final[
~sm_final['demo_code'].isin(
remove_age
)
]

ec_final = ec_final[
~ec_final['demo_code'].isin(
remove_age
)
]

#  — Final Demographic Harmonization

## Why?

Additional demographic categories were identified during validation.

Removed:

Y25_64
Y65_74

Reason:

These age groups fall outside project scope.

Final retained age groups:

Y16_24
Y25_54
Y55_74

Education labels for non-education rows were assigned:

"Not Education Segment"

to avoid missing categorical values.

In [443]:
sm_final.groupby(
['year','demo_code']
).size()

year  demo_code
2020  F_Y16_74      4
      M_Y16_74      4
      Y16_24        4
      Y16_24HI     14
      Y16_24LO     14
                   ..
2025  Y25_54LO     14
      Y25_54ME     14
      Y55_74HI     14
      Y55_74LO     14
      Y55_74ME     14
Length: 72, dtype: int64

In [444]:
ec_final.groupby(
['year','demo_code']
).size()

year  demo_code
2020  F_Y16_74      3
      IND_TOTAL     3
      M_Y16_74      3
      Y16_24        3
      Y16_24HI      9
                   ..
2025  Y25_54ME     10
      Y55_74        3
      Y55_74HI     10
      Y55_74LO     10
      Y55_74ME     10
Length: 78, dtype: int64

## Temporal Data Availability Note

Demographic coverage varied slightly across years.

Age and gender categories showed uneven availability in some years, while education-segmented observations remained available.

Consequently, yearly comparisons emphasize trend direction rather than absolute observation counts.

In [445]:
sm_final.groupby(
['year','education_level']
).size()

year  education_level
2020  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
2021  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
2022  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
2023  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
2024  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
2025  High Education           30
      Low Education            30
      Medium Education         30
      Not Education Segment    48
dtype: int64

In [446]:
ec_final.groupby(
['year','education_level']
).size()

year  education_level
2020  High Education           18
      Low Education            18
      Medium Education         18
      Not Education Segment    45
2021  High Education           21
      Low Education            21
      Medium Education         21
      Not Education Segment    45
2022  High Education           12
      Low Education            12
      Medium Education         12
2023  High Education           21
      Low Education            21
      Medium Education         21
      Not Education Segment    45
2024  High Education           10
      Low Education            12
      Medium Education         12
2025  High Education           21
      Low Education            21
      Medium Education         21
      Not Education Segment    45
dtype: int64

In [447]:
ec_final.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'demo_code', 'demographic', 'indicator_code', 'indicator', 'unit',
       'Unit of measure', 'country', 'Geopolitical entity (reporting)', 'year',
       'Time', 'value', 'Observation value', 'obs_flag',
       'Observation status (Flag) V2 structure', 'conf_status',
       'Confidentiality status (flag)', 'missing_flag', 'demo_type',
       'OBS_FLAG', 'CONF_STATUS', 'education_level'],
      dtype='str')

In [448]:
ec_final.groupby(
    ['year', 'indicator_code']
).size()

year  indicator_code
2020  I_B3_12            9
      I_BF_3-5          24
      I_BF_6-10         24
      I_BF_GT10         24
      I_BLT12            9
      I_BUY3             9
2021  I_B3_12            9
      I_BF_3-5          24
      I_BF_6-10         24
      I_BF_GT10         24
      I_BGT3             9
      I_BLT12            9
      I_BUY3             9
2022  I_B3_12            9
      I_BGT3             9
      I_BLT12            9
      I_BUY3             9
2023  I_B3_12            9
      I_BF_3-5          24
      I_BF_6-10         24
      I_BF_GT10         24
      I_BGT3             9
      I_BLT12            9
      I_BUY3             9
2024  I_B3_12            8
      I_BGT3             8
      I_BLT12            9
      I_BUY3             9
2025  I_B3_12            9
      I_BF_3-5          24
      I_BF_6-10         24
      I_BF_GT10         24
      I_BGT3             9
      I_BLT12            9
      I_BUY3             9
dtype: int64

In [449]:
ec_final['indicator_code'].unique()

<StringArray>
['I_BF_3-5', 'I_BF_6-10', 'I_BF_GT10', 'I_B3_12', 'I_BGT3', 'I_BLT12',
 'I_BUY3']
Length: 7, dtype: str

In [450]:
ec_final = ec_final[
ec_final['indicator_code'].isin([
'I_BF_1_2',
'I_BF_3-5',
'I_BF_6-10',
'I_BF_GT10',
'I_BUX'
])
]

In [451]:
ec_final.groupby(
['year','indicator_code']
).size().unstack(fill_value=0)

indicator_code  I_BF_3-5  I_BF_6-10  I_BF_GT10
year
2020                  24         24         24
2021                  24         24         24
2023                  24         24         24
2025                  24         24         24

# Data Availability Note

The e-commerce purchase-frequency indicators:

- I_BF_3-5
- I_BF_6-10
- I_BF_GT10

were unavailable for years 2022 and 2024 in the extracted Eurostat dataset.

Therefore:

- trend analysis emphasizes available years
- temporal interpretation focuses on behavioral patterns rather than continuous yearly frequency measurements

In [452]:
sm.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indicator_code,indicator,unit,Unit of measure,demo_code,demographic,country,Geopolitical entity (reporting),year,Time,value,Observation value,obs_flag,Observation status (Flag) V2 structure,conf_status,Confidentiality status (flag),missing_flag,demo_type
0,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2020,NaN,86.32,NaN,NaN,NaN,NaN,NaN,False,Gender
1,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2021,NaN,77.86,NaN,b,break in time series,NaN,NaN,False,Gender
2,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2022,NaN,78.91,NaN,NaN,NaN,NaN,NaN,False,Gender
3,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2023,NaN,81.94,NaN,NaN,NaN,NaN,NaN,False,Gender
4,dataflow,ESTAT:ISOC_CI_AC_I(1.0),Individuals - internet activities,A,Annual,I_IUEM,Internet use: sending/receiving e-mails,PC_IND,Percentage of individuals,F_Y16_74,"Females, 16 to 74 years old",DE,Germany,2024,NaN,84.85,NaN,NaN,NaN,NaN,NaN,False,Gender

In [453]:
ec.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,demo_code,demographic,indicator_code,indicator,unit,Unit of measure,country,Geopolitical entity (reporting),year,Time,value,Observation value,obs_flag,Observation status (Flag) V2 structure,conf_status,Confidentiality status (flag),missing_flag,demo_type
6,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_BF_3-5,Frequency of online purchases in the last 3 mo...,PC_IND,Percentage of individuals,DE,Germany,2020,NaN,26.81,NaN,NaN,NaN,NaN,NaN,False,Gender
7,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_BF_3-5,Frequency of online purchases in the last 3 mo...,PC_IND,Percentage of individuals,DE,Germany,2021,NaN,20.67,NaN,b,break in time series,NaN,NaN,False,Gender
8,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_BF_3-5,Frequency of online purchases in the last 3 mo...,PC_IND,Percentage of individuals,DE,Germany,2023,NaN,22.92,NaN,NaN,NaN,NaN,NaN,False,Gender
9,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_BF_3-5,Frequency of online purchases in the last 3 mo...,PC_IND,Percentage of individuals,DE,Germany,2025,NaN,21.80,NaN,NaN,NaN,NaN,NaN,False,Gender
10,dataflow,ESTAT:ISOC_EC_IB20(1.0),Internet purchases by individuals (2020 onwards),A,Annual,F_Y16_74,"Females, 16 to 74 years old",I_BF_6-10,Frequency of online purchases in the last 3 mo...,PC_IND,Percentage of individuals,DE,Germany,2020,NaN,15.44,NaN,NaN,NaN,NaN,NaN,False,Gender

In [454]:
sm.loc[
    sm['indicator_code'] == 'I_IUPH1',
    'indicator_name'
] = 'Internet Usage'

In [455]:
sm.to_csv(
    '../data/processed/germany_social_clean.csv',
    index=False
)

In [456]:
def assign_education_level(code):
    if code.endswith('HI'):
        return 'High Education'
    elif code.endswith('ME'):
        return 'Medium Education'
    elif code.endswith('LO'):
        return 'Low Education'
    else:
        return 'Not Education Segment'

sm['education_level'] = sm['demo_code'].apply(assign_education_level)

In [457]:
sm.to_csv("../data/processed/germany_social_clean.csv", index=False)

In [459]:
sm['indicator_name']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
859    NaN
860    NaN
861    NaN
862    NaN
863    NaN
Name: indicator_name, Length: 384, dtype: str